version: '3.5'

# TO USE A REAL CERTIFICATE
# First, replace the server_certificate.pem and server_key.pem with
# the real certificate and key.
#
# Next, replace the ca_certificate.pem file with the correct
# certificate authority bundle.
#
# There are two values in the section below marked with # Replace
# Change each of these values to the 'real' host name.

x-definitions: &env
    # IMPORTANT!!
    # Change this to whatever you want your garden name / namespace default to be
    BG_GARDEN_NAME: docker

    # IMPORTANT!!
    # Change this to support both local and remote plugins
    # Should be resolvable from inside and outside the docker network
    BG_PUBLISH_HOSTNAME: localhost

    # IMPORTANT!!
    # If you are connection to a Parent BG instance, toggle true
    BG_PARENT_HTTP_ENABLE: "false"

    # IMPORTANT !!
    # If you are connecting to a Parent BG instance, change this the resolvable DNS entry
    BG_PARENT_HTTP_HOST: localhost

services:
    ui:
        image: bgio/ui:unstable
        networks:
            - bg-network
        volumes:
            - ../data/certs:/certs
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "443:443"
        depends_on:
            - beer-garden

    beer-garden:
        image: bgio/beer-garden:unstable
        networks:
            - bg-network
        ports:
            - "2337:2337"
            - "2338:2338"
        volumes:
            - ../data/localplugins:/plugins
            - ../data/certs:/certs
            - ../data/logging-config.yaml:/src/example_configs/logging-config.yaml
        environment:
            <<: *env
            BG_DB_HOST: mongodb
            BG_DB_NAME: beer_garden_v3_docker_secure

            BG_NAMESPACES_LOCAL: docker_secure
            BG_ENTRY_HTTP_SSL_CA_CERT: "/certs/ca_certificate.pem"
            BG_ENTRY_HTTP_SSL_CLIENT_CERT_VERIFY: "NONE"
            BG_ENTRY_HTTP_SSL_ENABLED: "true"
            BG_ENTRY_HTTP_SSL_PRIVATE_KEY: "/certs/combined_server.pem"
            BG_ENTRY_HTTP_SSL_PUBLIC_KEY: "/certs/combined_server.pem"

            BG_MQ_HOST: rabbitmq
            BG_MQ_CONNECTIONS_ADMIN_USER: beer_garden
            BG_MQ_CONNECTIONS_ADMIN_PASSWORD: password
            BG_MQ_CONNECTIONS_ADMIN_PORT: "15671"
            BG_MQ_CONNECTIONS_ADMIN_SSL_ENABLED: "true"
            BG_MQ_CONNECTIONS_ADMIN_SSL_CA_CERT: "/certs/ca_certificate.pem"
            BG_MQ_CONNECTIONS_ADMIN_SSL_CA_VERIFY: "false"
            BG_MQ_CONNECTIONS_ADMIN_SSL_CLIENT_CERT: "/certs/combined_client.pem"

            BG_MQ_CONNECTIONS_MESSAGE_USER: beer_garden
            BG_MQ_CONNECTIONS_MESSAGE_PASSWORD: password
            BG_MQ_CONNECTIONS_MESSAGE_PORT: "5671"
            BG_MQ_CONNECTIONS_MESSAGE_SSL_ENABLED: "true"
            BG_MQ_CONNECTIONS_MESSAGE_SSL_CA_CERT: "/certs/ca_certificate.pem"
            BG_MQ_CONNECTIONS_MESSAGE_SSL_CA_VERIFY: "false"
            BG_MQ_CONNECTIONS_MESSAGE_SSL_CLIENT_CERT: "/certs/combined_client.pem"
        depends_on:
            - mongodb
            - rabbitmq

    mongodb:
        image: mongo:4.2
        networks:
            - bg-network
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb
        restart: always

    rabbitmq:
        image: rabbitmq:management-alpine
        restart: always
        hostname: rabbitmq
        networks:
            - bg-network
        environment:
            RABBITMQ_DEFAULT_USER: beer_garden
            RABBITMQ_DEFAULT_PASS: password

            RABBITMQ_SSL_CACERTFILE: /certs/ca_certificate.pem
            RABBITMQ_SSL_CERTFILE: /certs/combined_server.pem
            RABBITMQ_SSL_DEPTH: 2
            RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
            RABBITMQ_SSL_KEYFILE: /certs/combined_server.pem
            RABBITMQ_SSL_VERIFY: verify_peer

            RABBITMQ_MANAGEMENT_SSL_CACERTFILE: /certs/ca_certificate.pem
            RABBITMQ_MANAGEMENT_SSL_CERTFILE: /certs/combined_server.pem
            RABBITMQ_MANAGEMENT_SSL_DEPTH: 2
            RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: "false"
            RABBITMQ_MANAGEMENT_SSL_KEYFILE: /certs/combined_server.pem
            RABBITMQ_MANAGEMENT_SSL_VERIFY: verify_peer
        ports:
            - "5671:5671"
            - "15671:15671"
        volumes:
            - rabbitmq-home:/var/lib/rabbitmq
            - ../data/certs:/certs

networks:
    bg-network:
        driver: bridge
        name: bg-network

volumes:
    plugins:
    plugin-logs:
    mongo-data:
    mongo-config:
    rabbitmq-home:
