amq:
  admin_queue_expiry: 3600000
  blocked_connection_timeout: 5
  connection_attempts: 3
  connections:
    admin:
      password: guest
      port: 15672
      ssl:
        ca_cert: null
        ca_verify: true
        client_cert: null
        enabled: false
      user: guest
    message:
      password: guest
      port: 5672
      ssl:
        ca_cert: null
        ca_verify: true
        client_cert: null
        enabled: false
      user: guest
  exchange: beer_garden
  heartbeat_interval: 3600
  host: localhost
  virtual_host: /
db:
  connection:
    host: localhost
    password: null
    port: 27017
    username: null
  name: beer_garden
  ttl:
    action: -1
    event: 15
    info: 15
log:
  config_file: dev_conf/logging-config.json
  file: null
  level: INFO
plugin:
  local:
    auth:
      password: null
      username: null
    directory: ./plugins
    log_directory: null
    timeout:
      shutdown: 10
      startup: 2
  status_heartbeat: 5
  status_timeout: 30
publish_hostname: localhost
thrift:
  host: 0.0.0.0
  max_workers: 25
  port: 9090
web:
  ca_cert: null
  ca_verify: true
  host: localhost
  password: null
  port: 2337
  ssl_enabled: false
  url_prefix: null
  username: null
