name: Release Docker bgio/build Images

on: workflow_dispatch

jobs:

  docker-publish-python:
    name: Docker Publish bgio/build:python${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8.18", "3.9.18","3.10.13","3.11.6","3.12.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        working-directory: ./docker/dockerfiles/build
        run: make build-image-python${{ matrix.python-version }}

  docker-publish-rocky9-python:
    name: Docker Publish bgio/build:rocky9-python${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7.13", "3.8.18", "3.9.18","3.10.13","3.11.6","3.12.7"]

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Images
        working-directory: ./docker/dockerfiles/build
        run: make build-image-rocky9-python${{ matrix.python-version }}
